### ISSUE TITLE
Docs: Checkbox Example has the wrong argument/attribute

### ISSUE THREAD

**Issue by negue** [cmgriffing/react-streamdeck#10]
Example in the docs:
```jsx
<SDCheckbox
        label="Checkbox"
        checked={checkboxState}
        onChange={value => {
          console.log('I was changed.', value)
          setState({
            checkboxState: value,
          })
        }}
      />
```

1. There is no `checked` property, only a value
2. the `onChange` callback  needs something like `(event, value) =>`

**Comment by cmgriffing** [comment]
Thanks. This has now been fixed.
https://cmgriffing.github.io/react-streamdeck/components/checkbox
