### ISSUE TITLE
Bug: createUseGlobalSettings to use setGlobalSettings

### ISSUE THREAD

**Issue by negue** [cmgriffing/react-streamdeck#32]
If you currently use `createUseGlobalSettings`  it is saving the data to `setSettings` instead of 
`setGlobalSettings`

Docs for reference: 
https://developer.elgato.com/documentation/stream-deck/sdk/events-sent/#setglobalsettings

**Comment by negue** [comment]
using the branch: `fix-global-settings`


and this code:
```js
  const [settings, setSettings] = createUsePluginSettings({
    useState,
    useEffect,
    useReducer
  })(
    {
      buttonState: "",
      textState: "",
      numberState: 0,
      selectState: "",
      selectedListState: []
    },
    connectedResult
  );

  const [globalSettings, setGlobalSettings] = createUseGlobalSettings({
    useState,
    useEffect,
    useReducer
  })(
    {
      superString: "",
    },
    connectedResult
  );
 
  console.info('states', {
    globalSettings,
    settings
  });
```

Results in having globalSettings and settings - the same values, so I guess the normal settings somehow override the global ones

I guess it is because in `baseSettings.tsx` both states are overridden by 
```js
  if (connectedResult && connectedResult.actionInfo) {
        setState(connectedResult.actionInfo.payload.settings);
```

which only holds the normal settings not the global ones

**Comment by negue** [comment]
Newest update doesn't work: (newly created example project)  => https://github.com/negue/streamdeck-globalsettings-issue

Using the globalSettings the WSConnection seems to be not connected yet?

Console Errors:
```
common.js:37 Uncaught DOMException: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.
    at WebSocket.sendJSON (file:///C:/Users/Negue/AppData/Roaming/Elgato/StreamDeck/Plugins/com.acme.myStreamdeckPlugin.sdPlugin/common.js:37:8)
```

**Comment by cmgriffing** [comment]
Ok, thanks. I set the timeout too short. Works on my machine.

So instead I'm thinking I will just set an interval and poll the websocket connection until its connected.

**Comment by cmgriffing** [comment]
This should be working now, but my comment about polling the connection makes a lot of sense for an improvement..
